package com.home.trade.entity.enums;

public enum SymbolEnum {
    SUSHIUSDT("SUSHIUSDT"), INJUSDT("INJUSDT"), BNTUSDT("BNTUSDT"), TRXBUSD("TRXBUSD"),
    RDNTUSDT("RDNTUSDT"), ZRXUSDT("ZRXUSDT"), HIGHUSDT("HIGHUSDT"), WAVESUSDT("WAVESUSDT"),
    SPELLUSDT("SPELLUSDT"), XTZUSDT("XTZUSDT"), BNBUSDT("BNBUSDT"), DARUSDT("DARUSDT"),
    HNTUSDT("HNTUSDT"), JOEUSDT("JOEUSDT"), ETCUSDT("ETCUSDT"), XMRUSDT("XMRUSDT"),
    ALICEUSDT("ALICEUSDT"), HOOKUSDT("HOOKUSDT"), REEFUSDT("REEFUSDT"), BATUSDT("BATUSDT"),
    DOGEUSDT("DOGEUSDT"), TRXUSDT("TRXUSDT"), STORJUSDT("STORJUSDT"), SNXUSDT("SNXUSDT"),
    DOTBUSD("DOTBUSD"), XLMUSDT("XLMUSDT"), IOTXUSDT("IOTXUSDT"), UMAUSDT("UMAUSDT"),
    DASHUSDT("DASHUSDT"), KAVAUSDT("KAVAUSDT"), RUNEUSDT("RUNEUSDT"), APEUSDT("APEUSDT"),
    BLUEBIRDUSDT("BLUEBIRDUSDT"), BNXUSDT("BNXUSDT"), OPUSDT("OPUSDT"), KEYUSDT("KEYUSDT"),
    DGBUSDT("DGBUSDT"), SKLUSDT("SKLUSDT"), FOOTBALLUSDT("FOOTBALLUSDT"), TOMOUSDT("TOMOUSDT"),
    MTLUSDT("MTLUSDT"), LTCUSDT("LTCUSDT"), ETHBTC("ETHBTC"), KSMUSDT("KSMUSDT"),
    WAVESBUSD("WAVESBUSD"), BNBBUSD("BNBBUSD"), TRBUSDT("TRBUSDT"), MANAUSDT("MANAUSDT"),
    FLOWUSDT("FLOWUSDT"), CHRUSDT("CHRUSDT"), GALUSDT("GALUSDT"), USDCUSDT("USDCUSDT"),
    OGNUSDT("OGNUSDT"), RNDRUSDT("RNDRUSDT"), GALBUSD("GALBUSD"), STMXUSDT("STMXUSDT"),
    KNCUSDT("KNCUSDT"), SRMUSDT("SRMUSDT"), BLURUSDT("BLURUSDT"), ENJUSDT("ENJUSDT"),
    ATOMUSDT("ATOMUSDT"), SOLBUSD("SOLBUSD"), NMRUSDT("NMRUSDT"), ENSUSDT("ENSUSDT"),
    ATAUSDT("ATAUSDT"), AGIXUSDT("AGIXUSDT"), IOSTUSDT("IOSTUSDT"), HBARUSDT("HBARUSDT"),
    ZECUSDT("ZECUSDT"), IDEXUSDT("IDEXUSDT"), GALAUSDT("GALAUSDT"), EDUUSDT("EDUUSDT"),
    GTCUSDT("GTCUSDT"), ALGOUSDT("ALGOUSDT"), LRCUSDT("LRCUSDT"), AGIXBUSD("AGIXBUSD"),
    STGUSDT("STGUSDT"), STXUSDT("STXUSDT"), ARPAUSDT("ARPAUSDT"), CELOUSDT("CELOUSDT"),
    QNTUSDT("QNTUSDT"), INCHUSDT("INCHUSDT"), TUSDT("TUSDT"), LINAUSDT("LINAUSDT"),
    ARUSDT("ARUSDT"), ICP2USDT("ICP2USDT"), FILUSDT("FILUSDT"), SOLUSDT("SOLUSDT"),
    COMBOUSDT("COMBOUSDT"), MDTUSDT("MDTUSDT"), GMTUSDT("GMTUSDT"), XVSUSDT("XVSUSDT"),
    APTBUSD("APTBUSD"), GMXUSDT("GMXUSDT"), LDOBUSD("LDOBUSD"), BANDUSDT("BANDUSDT"),
    LDOUSDT("LDOUSDT"), XRPBUSD("XRPBUSD"), XRPUSDT("XRPUSDT"), CRVUSDT("CRVUSDT"),
    BELUSDT("BELUSDT"), DOTUSDT("DOTUSDT"), ONEUSDT("ONEUSDT"), APTUSDT("APTUSDT"),
    WAVEBUSD("WAVEBUSD"), ANKRUSDT("ANKRUSDT"), MAVUSDT("MAVUSDT"), API3USDT("API3USDT"),
    FTMBUSD("FTMBUSD"), LINKBUSD("LINKBUSD"), SANDBUSD("SANDBUSD"), ASTRUSDT("ASTRUSDT"),
    HOTUSDT("HOTUSDT"), IDBUSD("IDBUSD"), QTUMUSDT("QTUMUSDT"), IOTAUSDT("IOTAUSDT"),
    BTCBUSD("BTCBUSD"), ADAUSDT("ADAUSDT"), LITUSDT("LITUSDT"), UNIBUSD("UNIBUSD"),
    YFIUSDT("YFIUSDT"), ETHUSDT("ETHUSDT"), ALPHAUSDT("ALPHAUSDT"), WOOUSDT("WOOUSDT"),
    SFPUSDT("SFPUSDT"), RLCUSDT("RLCUSDT"), BTCSTUSDT("BTCSTUSDT"), FXSUSDT("FXSUSDT"),
    CFXUSDT("CFXUSDT"), AUDIOUSDT("AUDIOUSDT"), IDUSDT("IDUSDT"), HFTUSDT("HFTUSDT"),
    NEOUSDT("NEOUSDT"), UNFIUSDT("UNFIUSDT"), SANDUSDT("SANDUSDT"), CTKUSDT("CTKUSDT"),
    LINKUSDT("LINKUSDT"), MINAUSDT("MINAUSDT"), CELRUSDT("CELRUSDT"), RSRUSDT("RSRUSDT"),
    ADABUSD("ADABUSD"), RENUSDT("RENUSDT"), LPTUSDT("LPTUSDT"), JASMYUSDT("JASMYUSDT"),
    PHBUSDT("PHBUSDT"), EGLDUSDT("EGLDUSDT"), LUNA2USDT("LUNA2USDT"), ONTUSDT("ONTUSDT"),
    VETUSDT("VETUSDT"), IMXUSDT("IMXUSDT"), LQTYUSDT("LQTYUSDT"), COTIUSDT("COTIUSDT"),
    CVXUSDT("CVXUSDT"), ARBUSDT("ARBUSDT"), BAKEUSDT("BAKEUSDT"), GRTUSDT("GRTUSDT"),
    FLMUSDT("FLMUSDT"), GALABUSD("GALABUSD"), MASKUSDT("MASKUSDT"), EOSUSDT("EOSUSDT"),
    BALUSDT("BALUSDT"), SUIUSDT("SUIUSDT"), DENTUSDT("DENTUSDT"), TRUUSDT("TRUUSDT"),
    CKBUSDT("CKBUSDT"), SSVUSDT("SSVUSDT"), MATICBUSD("MATICBUSD"), C98USDT("C98USDT"),
    ZENUSDT("ZENUSDT"), NEARUSDT("NEARUSDT"), AMB("AMB"), AUCTIONBUSD("AUCTIONBUSD"),
    BCHUSDT("BCHUSDT"), LUNA2BUSD("LUNA2BUSD"), LTCBUSD("LTCBUSD"), ANTUSDT("ANTUSDT"),
    ETHBUSD("ETHBUSD"), AAVEUSDT("AAVEUSDT"), RADUSDT("RADUSDT"), AVAXUSDT("AVAXUSDT"),
    ARBBUSD("ARBBUSD"), MAGICUSDT("MAGICUSDT"), ROSEUSDT("ROSEUSDT"), MATICUSDT("MATICUSDT"),
    XVGUSDT("XVGUSDT"), MKRUSDT("MKRUSDT"), PEOPLEUSDT("PEOPLEUSDT"), ANCBUSD("ANCBUSD"),
    THETAUSDT("THETAUSDT"), UNIUSDT("UNIUSDT"), PERPUSDT("PERPUSDT"), RVNUSDT("RVNUSDT"),
    NKNUSDT("NKNUSDT"), KLAYUSDT("KLAYUSDT"), DEFIUSDT("DEFIUSDT"), COMPUSDT("COMPUSDT"),
    BTCDOMUSDT("BTCDOMUSDT"), BTCUSDT("BTCUSDT"), OMGUSDT("OMGUSDT"), ICXUSDT("ICXUSDT"),
    ICPBUSD("ICPBUSD"), FETUSDT("FETUSDT"), LEVERUSDT("LEVERUSDT"), FTMUSDT("FTMUSDT"),
    AMBUSDT("AMBUSDT"), AMBBUSD("AMBBUSD"), DOGEBUSD("DOGEBUSD"), SXPUSDT("SXPUSDT"),
    XEMUSDT("XEMUSDT"), ZILUSDT("ZILUSDT"), AXSUSDT("AXSUSDT"), DYDXUSDT("DYDXUSDT"),
    OCEANUSDT("OCEANUSDT"), LEVERBUSD("LEVERBUSD"), CHZUSDT("CHZUSDT"), DUSKUSDT("DUSKUSDT"),
    CTSIUSDT("CTSIUSDT"), ACHUSDT("ACHUSDT");

    private final String label;

    SymbolEnum(String label) {
        this.label = label;
    }

    public static boolean isSymbol(String value) {
        for (SymbolEnum en : values()) {
            if (value.equalsIgnoreCase(en.label)) {
                return true;
            }
        }
        return false;
    }
}
